name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        # export LINT_BRANCH=$(echo ${GITHUB_REF})
        # chmod u+x "run-lint-commited.sh"
        # npx eslint .
        # chmod u+x "checkJS.sh"
        # npm run checkJS --silent
        npm run build --if-present
        npm test --if-present
    - uses: tinovyatkin/action-eslint@v1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        check-name: eslint --ext .js # this is the check name from above 👆 where to post annotations        
      env:
        CI: true
