name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        chmod +x checkJS.sh
        npm run checkJS --silent
        npm run build --if-present
        npm test --if-present
    - name: eslint-github-pr-check
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.github_token }}
        eslint_flags: 'testdata/'
    - name: eslint-github-pr-review
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        eslint_flags: 'testdata/'        
      env:
        CI: true
    timeout-minutes: 3
